services:
  app:
    build:
      context: ./laravel-tutorial
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
        - docker-network
    ports:
      - 9000:9000
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: laravel_mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    volumes:
      - db-data:/var/lib/mysql
      # - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - docker-network
  nginx:
    image: nginx:alpine
    container_name: laravel-api-nginx
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - docker-network
  # queue-worker:
  #   build:
  #     context: ./laravel-best
  #     dockerfile: Dockerfile
  #   restart: unless-stopped
  #   networks:
  #     - docker-network
  #   depends_on:
  #     - db
  #   command: php artisan queue:work
  
  # caddy:
  #   image: caddy:latest
  #   ports:
  #     - 80:80
  #     - 443:443
  #   volumes:
  #     - ./laravel-best:/var/www/html
  #     - ./Caddyfile:/etc/caddy/Caddyfile
  #   networks:
  #     - docker-network
  #   depends_on:
  #     - app



  # redis:
  #   image: bitnami/redis:7.2
  #   platform: linux/amd64
  #   ports:
  #     - 6379:6379
  #   restart: always
  #   volumes:
  #     - redis-data:/bitnami/redis/data
  #   environment:
  #     - ALLOW_EMPTY_PASSWORD=no
  #     - REDIS_PASSWORD=${REDIS_PASSWORD}
  #     - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
  #   networks:
  #     - docker-network

volumes:
  db-data:
  redis-data:

networks:
  docker-network:
    driver: bridge